Grovy/ChameleonBusinessStudio

src/main/java/com/compilercharisma/chameleonbusinessstudio/config/OAuth2LoginSuccessHandler.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/config/SecurityConfiguration.java
Forgot to retire the 'Security' package, since everything is now under Config
=> Oops, forgot the success handler

angular-app/src/app/models/mock/mock-employees.ts
Forgot to add this file to my last PR, It's necessary for the tables in the admin panel to work and will fix any errors you might get if trying to run the app without this.
=> COM 211 - Adding additional file so tables can pull mock data from

src/main/java/com/compilercharisma/chameleonbusinessstudio/config/SecurityConfiguration.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentControllerv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/entity/AppointmentEntityv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/service/AppointmentServicev2.java
Merging branches on my local machine was scary, I just based this branch off of main and made sure that I included the changes y'all told me to make.
=> Com 219 rewrite of createAppointment

angular-app/src/app/app.module.ts, angular-app/src/app/models/interfaces/IUserResponse.ts, angular-app/src/app/pages/admin-panel/admin-panel-test/admin-panel-test.component.css, angular-app/src/app/pages/admin-panel/admin-panel-test/admin-panel-test.component.html, angular-app/src/app/pages/admin-panel/admin-panel-test/admin-panel-test.component.ts, angular-app/src/app/pages/admin-panel/admin-panel/admin-panel.component.html, angular-app/src/app/pages/admin-panel/admin-panel/admin-panel.component.ts, angular-app/src/app/services/UserService.service.ts
This PR consumes the API endpoint: `localhost:8080/api/users/getAllUsers` from our backend to display a table of all users registered to our Vendia database. 
- To see these changes make sure you have the Springboot project running and are logged in to an account.
- `UserService.service.ts` will be the service that calls the APIs to perform the CRUD operations on users. Right now I've only added the `getAllUsers()` function for this purpose but all other API calls will live here.
- Transferred all of our test admin panel data to `admin-panel-test` component. This component's purpose is just to serve as a guide for how we will structure our UI.
- Reorganized our `app-module.ts` file to follow alphabetical order.
Our admin panel showing users from Vendia:
Entity explorer in Vendia showing …
=> [COM 94] Display Users from Vendia in the Admin Panel

src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentControllerv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/dto/DeletionResponse.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/service/AppointmentServicev2.java
Created deleteAppointment endpoint and DeletionResponse class to connect to Vendia.
=> COM-221 Create /deleteAppointment Endpoint

angular-app/src/app/app.module.ts, angular-app/src/app/pages/dashboard/splash/splash.component.ts, angular-app/src/app/theme/modals/signup-modal/signup-modal.component.css, angular-app/src/app/theme/modals/signup-modal/signup-modal.component.html, angular-app/src/app/theme/modals/signup-modal/signup-modal.component.spec.ts, angular-app/src/app/theme/modals/signup-modal/signup-modal.component.ts
This PR creates an overlay modal that appears when a brand new user is detected. We detect this by searching the Vendia database for the email address of the person who just signed in. We will utilize a service endpoint to accomplish this and connect it to the login flow later.
Form asks user to enter a display name and we will save them as a new user in Vendia with the Participant role by default. Form contains validator to ensure they enter a name that matches the confirm display name field.
Create Account Button is disabled until the user enters a valid name that matches their confirmed display name.
=> COM 224 Create an Overlay that Prompts New Users to Enter Display Name and Consent

src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/AuthenticationController.java
This was already done in this controller, but now its just suited for Webflux, I want to do some integration tests on this, but right now, that does not seem easy to do with Spring Security blocking the way.
=> [COM-225] Get the email of the currently logged in user

angular-app/src/app/theme/modals/signup-modal/signup-modal.component.ts
This PR saves the new user to Vendia after signing in with Google. They will provide their display name and click save.
=> COM 226 Login Modal Registers New User

angular-app/src/app/app-routing.module.ts, angular-app/src/app/app.module.ts, angular-app/src/app/models/interfaces/IAvailability.ts, angular-app/src/app/models/interfaces/IEvent.ts, angular-app/src/app/models/mock/mock-availabile-times.ts, angular-app/src/app/pages/nav/nav.component.ts, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.css, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.html, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.spec.ts, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.ts
This PR creates the form for customizing a schedule based on the availability and event type (which will correspond to Appointment entities in the back end) based on the information provided here, the server will generate bookable appointments.
=> [COM 199] Customize Schedule Form

src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/UserController.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/service/AuthenticationService.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/service/UserService.java, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/service/UserServiceSpec.groovy, src/test/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentControllerTester.java
This PR basically makes an endpoint that gets a single user from Vendia based on the email passed, one thing that I need to know though, if is better if we pass the email as a header in the `UserController.java` class as opposed as a query parameter, we might not wanna just throw the email publicly in the route like: `/api/v2/users/getUser/danielV@gmail.com`.
Let me know your thoughts.
=> [COM-261] Make a get User endpoint

src/main/java/com/compilercharisma/chameleonbusinessstudio/client/VendiaClient.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentControllerv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/service/AppointmentServicev2.java, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositorySpec.groovy, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/service/AppointmntServiceSpec.groovy
Adds /getAppointments endpoint to return all appointments from the Vendia database.
=> COM-218 Create /getAppointments Endpoint

docs/routes.txt, src/main/java/com/compilercharisma/chameleonbusinessstudio/config/SecurityConfiguration.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentController.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/advice/InvalidAppointmentHandler.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/advice/NoUserLoggedInHandler.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/exception/NoUserLoggedInHandler.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/service/AppointmentService.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/service/AppointmentServicev2.java, src/test/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentControllerTester.java, src/test/java/com/compilercharisma/chameleonbusinessstudio/service/AppointmentServiceTester.java
Added the following API endpoints, as well as tons of unit tests:
- `POST /api/v1/appointments/cancel/{appt-id}`
- `POST /api/v1/appointments/unbook-me/{appt-id}`
- `POST /api/v1/appointments/unbook-them/{appt-id}?email={email}`
=> More api endpoints

angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.ts
This is the strategy to associate appointments with users. The first participant listed will be the Talent/Organizer for the appointment.
=> COM 265 Add Current User to Schedule Participant List

src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java
Made a way for the front-end to push multiple appointments if given a List of appointments. Needs some front-end help to fully be usable in our current project.
=> COM 252 createAppointments

src/main/java/com/compilercharisma/chameleonbusinessstudio/config/SecurityConfiguration.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/GlobalExceptionHandler.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/UserRepository.java, src/main/resources/application.properties, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/integration/UserControllerITSpec.groovy, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositorySpec.groovy, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/service/UserServiceSpec.groovy, src/test/resources/__files/vendiaResponses/createUserWithPhoneNumber.json
Really quick PR, now if the user includes a phone number when created then it will use the matching Vendia query that includes phone number, if not it'll just use the old one which works similarly.
=> [COM-275] Create user includes optional phone number

angular-app/src/app/models/interfaces/IUser.ts, angular-app/src/app/theme/modals/signup-modal/signup-modal.component.html, angular-app/src/app/theme/modals/signup-modal/signup-modal.component.ts
Adding an optional field to the first time sign up modal. The field is optional but when it detects that the user is entering something inside of the field, it will trigger the validation check to make sure it is a phone number entered in a valid format. Our app will automatically add the "+1" to the front of the number so the user only has to enter their number in format "XXXXXXXXXX".
=> COM 268 Adding an Optional Phone Number Field

src/main/java/com/compilercharisma/chameleonbusinessstudio/authentication/package-info.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/config/SecurityConfiguration.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentController.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/GlobalExceptionHandler.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/NotificationPreferencesController.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/ScheduleController.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/dto/Appointment.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/dto/HttpErrorMessage.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/dto/User.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/exception/ExternalServiceException.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/exception/InvalidAppointmentException.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/exception/InvalidScheduleException.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/exception/InvalidVendiaFieldException.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/exception/InvalidVendiaTypeException.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/exception/NoUserLoggedInException.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepository.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/UserRepository.java, src/main/java/com/compilercharisma/chameleonbusinessstudio/service/AppointmentService.java, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/authorization/UserAuthorizationManagerSpec.groovy, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/integration/UserControllerITSpec.groovy, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositorySpec.groovy, src/test/groovy/com/compilercharisma/chameleonbusinessstudio/service/AppointmentServiceSpec.groovy, src/test/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentControllerTester.java, src/test/java/com/compilercharisma/chameleonbusinessstudio/service/AppointmentServiceTester.java
1. Move the logic away from the `/book-them/{appointment-id}` away from the controller and into the service
2. Updated the `updateAppointment()` in `AppointmentRepository.java` and `AppointmentService.java`
3. Added UnsupportedOperationException into the `GlobalExceptionHandler.java`
4. Fixed some Integration tests regarding `UserController.java`
5. Added `serialVersionUID` to some of our Dtos 
6. Supressed some warnings in the code, e.g., logging while requesting parameters for logging, simplifying boolean logic, etc.
7. Removed the `/authentication` package since it did not have anything in it.
_Note: This broke some tests for AppointmentService, might need to fix later during the week_
=> More bugfixes for booking appointments

angular-app/src/app/app.module.ts, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.css, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.html, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.ts, angular-app/src/app/services/AppointmentDateFilterPipe.ts, angular-app/src/app/services/AppointmentService.service.ts
This is the first part of some changes going into our booking functionality. I used the `appointment-details.component` for this for now and will likely merge it to the `booking-page.component` once we have a calendar view from @Rojanmhj2055 . 
This part pulls the appointments directly from Vendia and formats them in a nice accordion table. Next steps are 1) Filter the appointments for viewing based on role and 2) Connecting booking functionality.
Admin/Talent View of their appointments
Participant View for being able to book the appointment
=> COM 274 Rework Some Cosmetics For the Booking Page

angular-app/src/app/models/interfaces/IAppointment.ts, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.css, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.html, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.ts, angular-app/src/app/pages/appointments/appointment-list/appointment-list.component.ts, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.ts, angular-app/src/app/services/AppointmentService.service.ts
1. Added more endpoints to the `AppointmentService.service.ts` file to consume in our app
2. 'appointment-details.component.ts` will consuming endpoints to react to appropriate button clicks
3. Added reactions to when a user books/unbooks an appointment.
To test the changes out:
1. Sign in to a participant account to book an appointment for yourself. Right now you CAN'T unbook yourself. Only a talent or admin account can unbook a user.
2. Sign in to a talent account to unbook an appointment. Haven't implemented admin/talent booking other users yet.
** Will be swapping the `/book-them` endpoint with `/book-me` for appropriate scenarios once #93 is merged. **
Example of participant book their own appointment:
Example of admin/talent unbooking an appointment:
=> COM 284 Booking Page Can Book and Unbook Appointments

angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.html, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.ts, src/main/java/com/compilercharisma/chameleonbusinessstudio/config/SecurityConfiguration.java
1. Swapping `/book-them/` with `/book-me` and adding the suffix to the end of the security configuration
=> Switching API endpoints in booking functionality

angular-app/src/app/app.module.ts, angular-app/src/app/pages/dashboard/splash/splash.component.css, angular-app/src/app/pages/dashboard/splash/splash.component.html, angular-app/src/app/theme/widgets/participant-booked-appts/participant-booked-appts.component.css, angular-app/src/app/theme/widgets/participant-booked-appts/participant-booked-appts.component.html, angular-app/src/app/theme/widgets/participant-booked-appts/participant-booked-appts.component.spec.ts, angular-app/src/app/theme/widgets/participant-booked-appts/participant-booked-appts.component.ts
1. Added a booked appointment widget on the participant's dashboard.
2. Allows the participant to unbook their own appointments.
3. Widget reacts based on actions and if no appointments found, it will display that message.
=> COM 283 Filtering Appointments Based on Current User

angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.css, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.html, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.ts, angular-app/src/app/theme/widgets/participant-booked-appts/participant-booked-appts.component.css
Added the ability for talent and admin accounts to book other users for available appointments.
Also added a piece to the card that displays the client who booked the appointment. Only visible to talent and admin accounts.
=> COM 285 Talent/Admin Can Book Other Users

angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.css, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.html, angular-app/src/app/pages/dashboard/splash/splash.component.css, angular-app/src/app/pages/dashboard/splash/splash.component.html, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.css, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.html, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.ts
Added Validation to the schedule form and placed it in a stepper flow component to make it more user friendly. Also added additional validation to the booking functionality in the `appointment-details.component`
=> COM 200 Client Side Validation of Schedule Form

angular-app/src/app/app.module.ts, angular-app/src/app/models/interfaces/IUser.ts, angular-app/src/app/models/mock/mock-employees.ts, angular-app/src/app/models/mock/mock-users.ts, angular-app/src/app/pages/admin-panel/admin-panel-test/admin-panel-test.component.ts, angular-app/src/app/pages/admin-panel/admin-panel/admin-panel.component.css, angular-app/src/app/pages/admin-panel/admin-panel/admin-panel.component.html, angular-app/src/app/pages/admin-panel/admin-panel/admin-panel.component.ts, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.html, angular-app/src/app/pages/appointments/appointment-details/appointment-details.component.ts, angular-app/src/app/pages/dashboard/splash/splash.component.css, angular-app/src/app/pages/dashboard/splash/splash.component.html, angular-app/src/app/pages/dashboard/splash/splash.component.ts, angular-app/src/app/pages/nav/admin-nav/admin-nav.component.ts, angular-app/src/app/pages/nav/participant-nav/participant-nav.component.ts, angular-app/src/app/pages/nav/talent-nav/talent-nav.component.ts, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.html, angular-app/src/app/pages/schedule-configuration/schedule-configuration.component.ts, angular-app/src/app/services/ScheduleService.service.ts, angular-app/src/app/services/UserService.service.ts, angular-app/src/app/theme/modals/signup-modal/signup-modal.component.ts, angular-app/src/app/theme/widgets/admin-panel-widget/admin-panel-widget.component.css, angular-app/src/app/theme/widgets/admin-panel-widget/admin-panel-widget.component.html, angular-app/src/app/theme/widgets/admin-panel-widget/admin-panel-widget.component.spec.ts, angular-app/src/app/theme/widgets/admin-panel-widget/admin-panel-widget.component.ts, angular-app/src/app/theme/widgets/event-widget/event-widget.component.css, angular-app/src/app/theme/widgets/event-widget/event-widget.component.html, angular-app/src/app/theme/widgets/event-widget/event-widget.component.ts, angular-app/src/app/theme/widgets/participant-booked-appts/participant-booked-appts.component.html, angular-app/src/index.html
=> Cleaning up Admin Panel + Adding Update User Role Functionality + Loading Spinners

README.md, src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/FileSystemWebsiteConfigurationRepository.java
RIP. That's what I get for copy pasting code and forgetting I did so until now.
=> forgot this
